apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  source:
    path: charts/kube-prometheus-stack
    repoURL: https://github.com/prometheus-community/helm-charts.git
    targetRevision: HEAD
    helm:
      valuesObject:
        alertmanager:
          enabled: false
        grafana:
          ingress:
            enabled: true
            ingressClassName: nginx
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt-production
            hosts:
              - grafana.k3s.fluv.net
            tls:
              - secretName: grafana-k3s-fluv-net-tls
                hosts:
                  - grafana.k3s.fluv.net
        kubeEtcd:
          enabled: false
        kubeScheduler:
          enabled: false
        cleanPrometheusOperatorObjectNames: true
        prometheusSpec:
          storageSpec:
            storageClassName: longhorn
            diskSelector: durable # i.e. not MicroSD
            resources:
              requests:
                storage: 50Gi
  project: monitoring
