apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
    kubernetes.io/description: |
      App of apps that defines all the other things Argo CD should manage
spec:
  project: default
  source:
    repoURL: https://github.com/zuzak/kube.git # this repo!
    path: apps
    targetRevision: HEAD
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      enabled: true
