apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
spec:
  project: default
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  source:
    path: ''
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 8.*
    chart: argo-cd
    helm:
      values: |
        global:
          domain: argocd.k3s.fluv.net
        server:
          ingress:
            enabled: true
            tls: true
            ingressClassName: nginx
            annotations:
              cert-manager.io/cluster-issuer: "letsencrypt-production"
              nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
