apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    kubernetes.io/description: |
      Generic project for assorted standard k8s definitions
spec:
  project: default
  source:
    repoURL: https://github.com/zuzak/kube.git # this repo!
    path: kube
    targetRevision: HEAD
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      enabled: true
