apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/zuzak/argo.git
    path: kube
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
