apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: mastodon
  namespace: argocd
spec:
  destinations:
  - name: in-cluster
    namespace: mastodon
    server: https://kubernetes.default.svc
  sourceRepos:
  - https://github.com/mastodon/chart.git
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mastodon
spec:
  destination:
    namespace: mastodon
    server: https://kubernetes.default.svc
  source:
    path: /
    repoURL: https://github.com/mastodon/chart.git
    targetRevision: HEAD
  project: mastodon
