apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: -20
spec:
  project: ingress
  source:
    repoURL: quay.io/jetstack/charts
    targetRevision: v1.18.2
    chart: cert-manager
    helm:
      values: |
        crds:
          enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      enabled: true
    syncOptions:
      - CreateNamespace=true
