apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: ingress
  namespace: argocd
spec:
  destinations:
  - namespace: nginx-ingress
    server: https://kubernetes.default.svc
  - namespace: cert-manager
    server: https://kubernetes.default.svc
  sourceRepos:
  - '*'
